### ISSUE TITLE
broken roman car servieces building , is not broken after installing the mod 

### ISSUE THREAD

**Issue by MehranAkbarii** [valentyn-l/GTAIV.EFLC.Various.Fixes#11]
![Uploading Grand Theft Auto 4 Screenshot 2023.11.18 - 13.57.57.24.png…]()

**Comment by Attramet** [comment]
Screenshot is not loading, but I assume it is save corruption. You had 1.6 installed previously? this may be caused because of some .ide file changes, but it needs to be checked.

**Comment by MehranAkbarii** [comment]
thanks , yes I think is related to my save and my save corrupted because of mod upgrading changes
