### ISSUE TITLE
Incorporate other mods onto this one

### ISSUE THREAD

**Issue by Sagatt** [valentyn-l/GTAIV.EFLC.Various.Fixes#12]
If possible incorporate other mods that you recommend onto this package, so we have a all-in-one definitive and easy to install package to fix the game whenever we need to, check fusion fix (fixes) and also other stuff such as DXVK and Grand Theft Auto IV and Episodes From Liberty City: Characters Fixes and also the Vehicle Pack 2.0 - 15th Anniversary Edition, thanks!

**Comment by valentyn-l** [comment]
Thanks for the suggestion!

We sadly already have our hand full with this project. However, you are more than welcome to make such a mod yourself. :)
