### ISSUE TITLE
Harboring a Grudge - black wall texture during first cutscene. 

### ISSUE THREAD

**Issue by r3538987** [valentyn-l/GTAIV.EFLC.Various.Fixes#13]
During first cutscene in Harboring a Grudge you can notice that certain wall textures becomes becomes black on certain distance or angle. 
![GIF 31 12 2023 19-42-31](https://github.com/valentyn-l/GTAIV.EFLC.Various.Fixes/assets/33725345/95748335-725f-4ea7-8d78-4a12a435398e)

Various.Fixes 1.81, if removed cutscene doesn't have black textures.

**Comment by valentyn-l** [comment]
Not an issue on my side using the latest 1.90 version. Please check your modlist/settings/saves and make sure it's not something on your end.
