### ISSUE TITLE
GTAIV.EFLC.Various.Fixes v1.81 (002 Corrupted)

### ISSUE THREAD

**Issue by SpockSmokesWeed** [valentyn-l/GTAIV.EFLC.Various.Fixes#14]
Hi there. I downloaded part 2 for Various Fixes version 1.81 and the file said it was corrupted. It was a ".002" file and I tried opening it with winrar but it did not like that.

**Comment by valentyn-l** [comment]
Hi. You must download parts 001 and 002, then extract 001. It will automatically extract the contents of 002 along with it.
