### ISSUE TITLE
2 different light models on a parking hut

### ISSUE THREAD

**Issue by UnknownLITE** [valentyn-l/GTAIV.EFLC.Various.Fixes#18]
![image](https://github.com/valentyn-l/GTAIV.EFLC.Various.Fixes/assets/91004913/6659dc5c-d1ef-4e27-afd2-32f7c59fec6b)
![image](https://github.com/valentyn-l/GTAIV.EFLC.Various.Fixes/assets/91004913/44140efd-00c0-4923-b46d-8fda1fe86ce9)

**Comment by valentyn-l** [comment]
Fixed
![20240630222904_1](https://github.com/valentyn-l/GTAIV.EFLC.Various.Fixes/assets/60371520/904006a1-e045-43af-ae06-6aad7a809d84)
