### ISSUE TITLE
Problem when using Manual Installation

### ISSUE THREAD

**Issue by RealDawTheD** [valentyn-l/GTAIV.EFLC.Various.Fixes#20]
![image](https://github.com/valentyn-l/GTAIV.EFLC.Various.Fixes/assets/82605931/b92b69f7-f6ff-4dd0-8146-c439f51fa804)

Happens with IV, TLAD and TBoGT

**Comment by netskycz** [comment]
Ah, the classic file name conflict during manual installation. It’s almost like the computer expects us to be mind readers and know that "cuts.img" already exists. So, how about we try renaming the file to something different, like "cuts_v2_final_final_final.img"? Or even better, "cuts_v2_here_we_go_again.img"? Who knows, maybe we’ll confuse the computer so much that it’ll just let us proceed!

Good luck and stay strong!
