### ISSUE TITLE
all .img are folders not files, can't replace

### ISSUE THREAD

**Issue by 0bsidianFox** [valentyn-l/GTAIV.EFLC.Various.Fixes#21]
all .img is in folder format, not as actual .img files in manual Installation.
![image](https://github.com/valentyn-l/GTAIV.EFLC.Various.Fixes/assets/72424605/902b2fda-b71d-4156-a740-e475ef5c858f)

**Comment by valentyn-l** [comment]
You must use an .img explorer such as OpenIV to open and replace files within the game's .imgs.
