### ISSUE TITLE
flooting light

### ISSUE THREAD

**Issue by yukkuri4934** [valentyn-l/GTAIV.EFLC.Various.Fixes#22]
please fix
![IMG_0450](https://github.com/valentyn-l/GTAIV.EFLC.Various.Fixes/assets/174004032/8a7e25c6-2254-44c8-9d9e-6ff9f0965ede)
![IMG_0451](https://github.com/valentyn-l/GTAIV.EFLC.Various.Fixes/assets/174004032/add1d39a-2de4-496b-8375-49279e69b001)
![IMG_0452](https://github.com/valentyn-l/GTAIV.EFLC.Various.Fixes/assets/174004032/f2952fcf-6386-4cff-860e-2187c2c93f7e)

**Comment by valentyn-l** [comment]
Fixed
![20240630221252_1](https://github.com/valentyn-l/GTAIV.EFLC.Various.Fixes/assets/60371520/f0ad2439-3adb-4ef4-ad4c-81d9733e214e)

**Comment by yukkuri4934** [comment]
Im sorry
I forgot to mention
Other lights in the area are also broken.
