### ISSUE TITLE
parking line

### ISSUE THREAD

**Issue by yukkuri4934** [valentyn-l/GTAIV.EFLC.Various.Fixes#23]
Describe the issue in as much detail as possible
![IMG_0453](https://github.com/valentyn-l/GTAIV.EFLC.Various.Fixes/assets/174004032/e11d8c4c-fad0-4515-8566-19b38788814b)

**Comment by valentyn-l** [comment]
Do you mean the white paint streak under the tires? If so, the game is riddle with instances like these. These can cause z-fighting if placed too close to the ground. It is also a can of worms that the VF team is not tackling atm.
