### ISSUE TITLE
ground is conclete

### ISSUE THREAD

**Issue by yukkuri4934** [valentyn-l/GTAIV.EFLC.Various.Fixes#24]
looks like gravel  But it's concrete
![IMG_0454](https://github.com/valentyn-l/GTAIV.EFLC.Various.Fixes/assets/174004032/2cdf3a87-9f2b-4aa7-bd39-a18ed9078f7f)
![IMG_0455](https://github.com/valentyn-l/GTAIV.EFLC.Various.Fixes/assets/174004032/b144b6d4-5f77-4d19-9d45-3e09e3cdb1dc)

**Comment by valentyn-l** [comment]
Fixed

Before
![Screenshot 2024-06-30 210251](https://github.com/valentyn-l/GTAIV.EFLC.Various.Fixes/assets/60371520/b0754947-489d-46ae-9513-660b379cc353)
After
![Screenshot 2024-06-30 205959](https://github.com/valentyn-l/GTAIV.EFLC.Various.Fixes/assets/60371520/11438246-685d-4202-b64d-1901164d0f2a)
