### ISSUE TITLE
[Habanero] Turn signal 

### ISSUE THREAD

**Issue by yukkuri4934** [valentyn-l/GTAIV.EFLC.Various.Fixes#26]
Habanero is turn signal is white (front)
but light reflection road is amber

**Comment by valentyn-l** [comment]
Images please

**Comment by yukkuri4934** [comment]
![Base Profile Screenshot 2024 07 28 - 14 03 11 16](https://github.com/user-attachments/assets/d9a1fa1e-069c-4fab-b5d9-a01213682759)
 not amber color

**Comment by valentyn-l** [comment]
There is no issue with the headlighs colour. This is intended

GTA IV habanero headlight texture:
![image](https://github.com/user-attachments/assets/9b81db75-37d7-4149-aca7-351c08d5fd9d)

GTA V Habanero:
![image](https://github.com/user-attachments/assets/4b0ab523-8070-4119-9fe4-d7d255e140f0)
