### ISSUE TITLE
Bohan ground shadow

### ISSUE THREAD

**Issue by yukkuri4934** [valentyn-l/GTAIV.EFLC.Various.Fixes#28]
Describe the issue in as much detail as possible
![IMG_0499](https://github.com/user-attachments/assets/937de606-75f5-42a2-b0a2-44873f5d93de)
![IMG_0500](https://github.com/user-attachments/assets/cf82d052-bbbd-440f-a259-1576cd37f3c8)

**Comment by valentyn-l** [comment]
Fixed
![image](https://github.com/user-attachments/assets/f29bd146-257f-4b67-8573-323fdcbe47ba)
