### ISSUE TITLE
perennial2 roof light

### ISSUE THREAD

**Issue by yukkuri4934** [valentyn-l/GTAIV.EFLC.Various.Fixes#31]
Is this what the developers intended?
Or is it a mistake?
I do not know.
![Base Profile Screenshot 2024 07 28 - 15 02 33 31](https://github.com/user-attachments/assets/f09d55b9-2cd2-4ad8-82ef-1fa5dc7a0818)

**Comment by valentyn-l** [comment]
What are the names of the car models?

**Comment by yukkuri4934** [comment]
PERENNIAL2  please fix

**Comment by valentyn-l** [comment]
Fixed. Will be available in the next FusionFix release
![image](https://github.com/user-attachments/assets/ce87da79-ec3d-4fbc-9c97-259f9d98ee32)
