### ISSUE TITLE
tire blackmark mistake

### ISSUE THREAD

**Issue by yukkuri4934** [valentyn-l/GTAIV.EFLC.Various.Fixes#33]
Not double tires
ambulance,firetruck,stockade,nstockade,pstockade.

![Base Profile Screenshot 2024 07 28 - 16 51 20 31](https://github.com/user-attachments/assets/d6b2e894-a774-438d-8e47-a0a08bfeaed5)

![Base Profile Screenshot 2024 07 28 - 16 51 48 33](https://github.com/user-attachments/assets/6d10e247-8ebf-447b-b014-1879d6fbfc42)
![Base Profile Screenshot 2024 07 28 - 16 53 46 42](https://github.com/user-attachments/assets/c37e50b2-1db9-479b-8b1b-51137577b322)
![Base Profile Screenshot 2024 07 28 - 16 54 16 87](https://github.com/user-attachments/assets/686ae738-6ed3-491e-b72d-837de1b4277d)
![Base Profile Screenshot 2024 07 28 - 16 56 39 97](https://github.com/user-attachments/assets/254a555d-3ff6-426e-98ef-ad7fab26bc5c)

**Comment by valentyn-l** [comment]
There are flags that can be set in handling.ide which control this (double wheels, wheel types on front/back) but apparently, they do nothing when set

**Comment by yukkuri4934** [comment]
![IMG_0502](https://github.com/user-attachments/assets/1e8ba11e-d327-4440-94f8-020192fc391f)
Is this a problem with the vehicles.img？？
I hope this problem can be solved

**Comment by valentyn-l** [comment]
Could you test more trucks/vehicles for this issue please? Would really help out

**Comment by yukkuri4934** [comment]
I checked all the tracks
bus,benson,biff,boxville,flatbed,mrtasty,mule, packer,phantom,ripley,steed,trash,yankee,
There were no problems with these

**Comment by valentyn-l** [comment]
![20240731010948_1](https://github.com/user-attachments/assets/858e8019-31ba-462f-852e-6140232f54c3)
![20240731011103_1](https://github.com/user-attachments/assets/472fb672-9f2b-45c0-998d-342bcbae1569)
Ambulance is fixed and will be included in the next release of FusionFIx

The remaining vehicles will be fixed shortly

**Comment by yukkuri4934** [comment]
it is really amazing
Nobody tried to solve this problem
I am very grateful!!

**Comment by valentyn-l** [comment]
All of them have been fixed and will appear in the next release of FF. Double wheels have been added to all vehicles except the n, p and regular stockade versions due to incompatibility with the body model. As such, those stay as single wheel at the back, but the skids are correct now
