### ISSUE TITLE
Broker no collision wall

### ISSUE THREAD

**Issue by yukkuri4934** [valentyn-l/GTAIV.EFLC.Various.Fixes#35]
no collision wall
![r](https://github.com/user-attachments/assets/888c1c7d-d198-49ee-82f1-4e36112835de)
![w](https://github.com/user-attachments/assets/6f709559-eca2-47b2-a519-45502365e1b5)

**Comment by valentyn-l** [comment]
Fixed in both IV and TBOGT
![image](https://github.com/user-attachments/assets/527c5f3b-cb9e-4796-b42a-dd5d43c971e7)
