### ISSUE TITLE
Additional fixes

### ISSUE THREAD

**Issue by yukkuri4934** [valentyn-l/GTAIV.EFLC.Various.Fixes#36]
The problem wasn't just one thing.

※ground mistake

![a](https://github.com/user-attachments/assets/397f3ef7-73ac-4d7d-84a9-0dc95a4be2c2)
![s](https://github.com/user-attachments/assets/db5b9df4-5fab-4aad-bf18-accd2a2dd360)

※light position mistake

![r](https://github.com/user-attachments/assets/e51157cb-cc62-4c38-b5fa-1d84a8f8b026)
![f](https://github.com/user-attachments/assets/d140e0f4-b9e5-4aea-84c6-88a47ce11087)

**Comment by valentyn-l** [comment]
Both have been fixed. The first example was the incorrect collision material, second was the lights which I fixed when fixing the previously reported misaligned light
