### ISSUE TITLE
car head light bug

### ISSUE THREAD

**Issue by yukkuri4934** [valentyn-l/GTAIV.EFLC.Various.Fixes#42]
this place no light visual
![g](https://github.com/user-attachments/assets/e77d0bed-7da7-42c4-906d-a4c3d705bab7)
![t](https://github.com/user-attachments/assets/e084685e-53c6-48af-9863-b6b62cb1b0b4)
![tye](https://github.com/user-attachments/assets/aa19e440-38d5-4ea3-a9ac-9411bcc9c7f4)

**Comment by valentyn-l** [comment]
Not sure what you mean. There's no headlight?

**Comment by valentyn-l** [comment]
Assuming that you do not have Console Lights installed which removes the shadows from secondary point lights, this is a limitation of the game's engine. It can only render so many dynamic shadow-casting lights. As such, it will begin turning off lights which go beyond the limit. 

Below is the latest FF preview with Console-style lights which do not cast shadows:
![20240803152311_1](https://github.com/user-attachments/assets/45707ae4-7cc1-4996-a9dd-35d0743a5746)

If you would like to achieve this result, either wait for the nest FF release or install this mod 

https://gtaforums.com/topic/989098-console-visuals-the-complete-edition/

**Comment by yukkuri4934** [comment]
This was my problem
I was using console visual
but 1.0.8.0
1.2.0.59 is fixed
I'msorry
![w](https://github.com/user-attachments/assets/1d31435f-6f05-4ebb-a196-3eb20383e9d3)
