### ISSUE TITLE
Bohan object

### ISSUE THREAD

**Issue by yukkuri4934** [valentyn-l/GTAIV.EFLC.Various.Fixes#44]
1
![r (3)](https://github.com/user-attachments/assets/e55a5c89-c270-4016-aad5-7ef8e27f1229)
![y (1)](https://github.com/user-attachments/assets/9ba02752-ace5-45ca-924b-5e9f9f8b0164)
![y (2)](https://github.com/user-attachments/assets/8d62e483-394c-438e-8d64-4ab19d14129f)

2
![r (1)](https://github.com/user-attachments/assets/44367955-2dcb-4552-888d-3b6bd01109d8)
![r (2)](https://github.com/user-attachments/assets/5733ffad-5497-473e-a998-5e03a2ee07e0)
 3
![m (1)](https://github.com/user-attachments/assets/b5ec048b-af06-4a20-8b8c-cd2b22258ae8)
![m (2)](https://github.com/user-attachments/assets/70ed315c-f9f1-412f-9eb3-011aca714723)

**Comment by valentyn-l** [comment]
These are all procedurally placed. This will happen at random no matter what
