### ISSUE TITLE
WIndows and objects flickering

### ISSUE THREAD

**Issue by Ashwath6531** [valentyn-l/GTAIV.EFLC.Various.Fixes#48]
Most of the windows in this game seem to be glitched and keep flickering for me. This includes the subway stations, the toll booth, and the Burger Shots. Also, the curtains, leaves of the plant by the wardrobe, and the coffee machine in the Bohan safehouse all keep flickering.

![12210_20240810144839_1](https://github.com/user-attachments/assets/f53d22f0-e8a2-42ef-aab5-7e2ad7c09c1e)

![12210_20240810144849_1](https://github.com/user-attachments/assets/f4f635a4-1c87-4e60-8d89-e4adc8e8cb7a)

**Comment by valentyn-l** [comment]
Are you using FusionFix?

There is no flicker for me whatsoever on most windows.

**Comment by Ashwath6531** [comment]
> Are you using FusionFix?
> 
> There is no flicker for me whatsoever on most windows.

Yes I am

**Comment by Ashwath6531** [comment]
I take it it's just most glasses in the game and not just windows. 
![12210_20240810175920_1](https://github.com/user-attachments/assets/b85ab7fb-07ed-4996-97ae-2ae04ffd6574)
![12210_20240810180759_1](https://github.com/user-attachments/assets/4e28071f-47f3-48cd-b101-716ea8bcbf3f)

**Comment by Attramet** [comment]
This has nothing to do with Various Fixes, look for the reason in other mods you have installed
