### ISSUE TITLE
[Vanilla Bug Report?] Big truck horn perpetually heard from building in Alderney City, Jonestown Avenue

### ISSUE THREAD

**Issue by Abbanon** [valentyn-l/GTAIV.EFLC.Various.Fixes#62]
In this location, at the building pictured, you can hear the horn of a large vehicle (think of a semi/18-wheeler) being perpetually held down.
No-clipping into the environment shows nothing, there is no vehicle in either the building or the ground below.
I would post a clip but my recording software does not want to capture audio from GTA IV.
I'm not sure what could be causing this, or if it's a vanilla game issue.
![Screenshot_3](https://github.com/user-attachments/assets/b4c27113-2695-4948-9f58-3e8d1700ccda)

**Comment by RecklessGlue540** [comment]
Yes, it's a vanilla issue, happening on console, and is completely random and can happen anywhere. It's maybe something related to memory, or in any case, an issue in the original game code, meaning it's probably not wise to report it here, but on here:
https://github.com/GTAmodding/GTAIV-Issues-List/issues
and of course, perhaps it was probably reported a few times on there already, so you should check if it was, and if it was, probably don't create a new one.
