### ISSUE TITLE
2.0 Glitch The road and shadows disappear when standing at the door.

### ISSUE THREAD

**Issue by Dx360** [valentyn-l/GTAIV.EFLC.Various.Fixes#65]
The exterior is blurred when inside the building.

**Comment by Dx360** [comment]
The road and shadows disappear when standing at the door.

**Comment by valentyn-l** [comment]
Come again?

**Comment by Dx360** [comment]
Yes sir

**Comment by valentyn-l** [comment]
Where's the picture? I don't know what you mean.

**Comment by Dx360** [comment]
![image](https://github.com/user-attachments/assets/d231fc48-521d-4d6e-aaaf-07c6ca0259f8)

**Comment by Dx360** [comment]
![image](https://github.com/user-attachments/assets/ffc80bca-54b8-4e1d-8e60-9d2c19799a3d)

**Comment by Dx360** [comment]
![image](https://github.com/user-attachments/assets/bc7db572-15fa-45f1-a710-20b24e8972d4)
![image](https://github.com/user-attachments/assets/f020a096-a9a0-4c61-82c5-1fef5749527b)

**Comment by valentyn-l** [comment]
This is normal behaviour and nothing can be done about it afaik. It's just the way the game handles interiors. 

Shadows are also disabled in the exterior when in an interior space, but this is behaviour that changed with patch 1.0.5.0 I believe
