### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by vavrinko** [valentyn-l/GTAIV.EFLC.Various.Fixes#9]
Hi.
First of all, I love your mod. But I have one question and one problem.
This is how Bahama Mamas looks for me in daytime.
![image](https://github.com/valentyn-l/GTAIV.EFLC.Various.Fixes/assets/96373757/5b6c8118-bb96-462b-875e-7d13e3e2db88)

How am I to fix it? I tried this on 1.0.8.0 and 1.0.32. with fusion overloader installation.

And I have the question about the night shadows as well. How do I re-enable them?

**Comment by Attramet** [comment]
So what's wrong about this? this is how Bahama Mamas looks in IV, neons turns on at night and turns off during day.
You mean re-enable them for lampposts? well you can do this with ZPatch, but shadows will look buggy, this was already discussed on gtaforums mod page.

**Comment by vavrinko** [comment]
Yes, sorry for not specifying. I meant the white and pink lights. Shouldn't they be off as well during the day?

ZPatch you mean Zolika patch? Do you know which setting it is?
Fusion Fix, corrects some of them and fixes the flickering.

**Comment by Attramet** [comment]
Oh, these lights, well, maybe they should turn off along with the neons, but I don’t know how to work with light sources at all, so the question remains open.
I can't say exactly what option, but it's definitely related to shadows, although I used old version of that patch, so idk about new one

**Comment by vavrinko** [comment]
I see. Hmm. Thanks for the answer anyway.
Considering the lights. I found the option in Zpatch. It makes the shadows flicker however, even with the Fusion Fix.

Would it be possible to make the shadows optional in your mod? Because Fusion is fixing some of them. It isn't perfect and some of the lamp poles still have double shadows, but the improvements are actually really nice.
https://imgur.com/ESPa2eR

And I'd really like to use the combo of your mod with it.
Maybe something I can do with openIV  to make the shadows appear?

**Comment by vavrinko** [comment]
nvm. I found out what to do. I am glad I can use it now without any problem.

Thank you for the mod.
All the best :)
